### PR TITLE
Addition of `params` argument

### PR DESCRIPTION
**Pull request by hrj21**
Hi Chris,

Thanks for creating this package, I've been using it a lot lately. We're comparing the data we get from a bunch of the new Starbright dyes on our Aurora, Fortessa, and ZE5 and want to look at the "spectra" of each. Because I wanted to order the parameters of the Fortessa and ZE5 in the same excitation wavelength order as the Aurora, I added a `params` argument to the two functions from you package which defaults to NULL. If left as NULL, the functions behave exactly as they did, but if the data do not come from an Aurora, BigFoot, or ID7000, and the params argument is given, the parameters are plotted in the order given to this argument as a character vector.

I haven't made a pull request before, so I hope I'm doing this right! If it's of no use to you then don't worry about it, but if it is then please do some testing on your end that I haven't broken anything.

Best wishes
Hefin

### CODE REVIEW

**Comment by hally166** [comment]
Thanks Hefin,  it looks good, I'll test it and make sure it works on my data too before merging it into the main branch.  TBH, I think a params argument will be useful on any of the instruments.  I deal with exported FlowJo data, and when FlowJo creates a new FCS file it annoyingly reorders the parameters.

**Comment by hrj21** [comment]
Ah ok great. In which case would you like me to change it so that it applies irrespective of instrument? At present, params is only used if $CYT isn't Aurora, ID7000, or BigFoot.

As an aside, do you have any plans for including your unmixing script in the package?

**Comment by hally166** [comment]
That would be great if you could.  I've been working on some rudimentary auto-gating to try and create pure spectra that I'm testing at the moment.   

As for unmixing, so specific plans as there are other tools out there to do this and it's not very difficult to do at all, the hardest part is creating clean controls.  Having said that, if I can get the autogating to work well...

I'll update this to be more useful in 5 minutes:
[Unmixing by hand](https://github.com/hally166/Cytometry-R-scripts/blob/master/unmix_by_hand.R)

**Comment by hrj21** [comment]
Hey Chris, so I've pushed a change that means if the params argument is not NULL, the user-specified vector of parameters is used, otherwise it will use the instrument-specific parameters you set up, and if params is NULL, and $CYT isn't aurora, bigfoot, or ID7000, it will use the fallback "I will try to guess but might get it wrong" set of parameters. Again, please test and make sure you agree.

**Review by hally166 — APPROVED** [review]
Looks good to me.  I'll bump the version and add a description of how the params argument should look in the readme.

**Pull request merged**
